feat!: update colors, dependencies
gravity-ui/paranoid pull request #29
Opened 2024-04-12 13:31 UTC by Raubzeug

2024-04-18 16:20 UTC, SeqviriouM approved these changes

2024-04-18 17:27 UTC, amje requested changes

2024-04-18 17:27 UTC, amje commented on package.json
> +    "@gravity-ui/uikit": "^6.10.2",
It shouldn't depend on that

2024-04-19 09:08 UTC, amje approved these changes

2024-04-19 09:52 UTC, merged